template_path: sqs.yaml
stack_name: sqs-fargate-consumer-eventqueue
parameters:
  ScProductVersion: 1.0.9
  QueueName: "sqs-fargate-consumer-eventqueue"
  VisibilityTimeout: "300"
  MaxReceiveCount: "10"